dist: trusty
language: node_js
node_js:
  - stable
addons:
  sonarcloud:
    organization: "docwhat"
    token:
      secure: "XwcXk9ZecDYtVhal+UnoGVy/jEzhMAucvQTnPXzFgNcQdBj5t+mcF0juvL/1eEbQSZK60gZja11D8tUF5wnZyOmfx034XOA6Iec/fYSaW8RJo6kdb3Pha3z8htAJ4E2skoCovmIntEWWoguybgiaP+wtN0jyW2avVQAuWGoKkkw=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
